local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  inflation_radius: 2.0
  update_frequency: 6.0
  publish_frequency: 6.0
  static_map: false
  rolling_window: false
  width: 5.0
  height: 5.0
  resolution: 0.04
  track_unknown_space: false 
  plugins: 
    - {name: static_layer,              type: "costmap_2d::StaticLayer"}
    # - {name: laser_obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    # - {name: kinect_obstacle_layer,     type: "costmap_2d::ObstacleLayer"}
    - {name: simulation_obstacle_layer, type: "rose_costmap_2d_plugins::SimulationObstacleLayer"}
    - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}
